application: thenextmuse
version: test
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "latest"

builtins:
- admin_redirect: on
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /themes
  static_dir: templates/themes

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /login/google
  script: main.app
  login: required

- url: /admin/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
