application: thenextmuse
version: 1
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /login/google
  script: main.py
  login: required

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
