application: journalr-org
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: django
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /login/google
  script: main.app
  login: required

- url: /admin/.*
  script: main.app
  login: admin

- url: /tasks/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
