application: missao-rio
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /styles
  static_dir: static/styles

- url: /imgs
  static_dir: static/imgs

- url: /js-static
  static_dir: static/js

- url: /files
  static_dir: static/files

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin

- url: /_ah/missao-rio/.*
  script: main.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /.*
  script: main.py

admin_console:
  pages:
  - name: MapReduce
    url: /mapreduce/

  - name: Map Control
    url: /_ah/missao-rio/map-control/

  - name: Sync Areas
    url: /_ah/missao-rio/sync-areas/

derived_file_type:
- python_precompiled
