application: missao-rio
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /styles
  static_dir: static/styles

- url: /imgs
  static_dir: static/imgs

- url: /js-static
  static_dir: static/js

- url: /missionaries
  static_dir: static/missionaries

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
#  login: admin

- url: /.*
  script: main.py
