application: missao-rio
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /styles
  static_dir: static/styles

- url: /imgs
  static_dir: static/imgs

- url: /js-static
  static_dir: static/js

- url: /files
  static_dir: static/files

- url: /missionaries
  static_dir: static/missionaries

- url: /discursos-files/
  static_dir: static/discursos

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /_ah/bulkupdate/admin/.*
  script: bulkupdate/handler.py
  login: admin

- url: /_ah/nuke/.*
  script: nuke/nuke.py
  login: admin

- url: /_ah/missao-rio/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py

admin_console:
  pages:
  - name: Check Photos
    url: /_ah/missao-rio/check/
  - name: Dump
    url: /_ah/missao-rio/dump/
  - name: Sync Areas
    url: /_ah/missao-rio/sync-areas/

  - name: Bulk Update Jobs
    url: /_ah/bulkupdate/admin/

  - name: Nuke
    url: /_ah/nuke/

derived_file_type:
- python_precompiled

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^discursos/
- ^mk_disc.py
