application: nyc-now
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: latest
- name: webapp2
  version: latest

builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
