application: missao-rio
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /styles
  static_dir: static/styles

- url: /themes
  static_dir: static/themes

- url: /imgs
  static_dir: static/imgs

- url: /missionaries
  static_dir: static/missionaries

- url: /js-static
  static_dir: static/js

- url: /files
  static_dir: static/files

- url: /_ah/missao-rio/.*
  script: main.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /.*
  script: main.py

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats/

  - name: Mission Status
    url: /_ah/missao-rio/status/

  - name: Choose Week
    url: /_ah/missao-rio/choose-week/

  - name: Make New
    url: /_ah/missao-rio/make-new/

  - name: MapReduce
    url: /mapreduce/

  - name: Map Control
    url: /_ah/missao-rio/map-control/

  - name: Indicator Check
    url: /_ah/missao-rio/indicator-check/

  - name: Enter RPM
    url: /_ah/missao-rio/enter-rpm/

  - name: Make Batismos
    url: /_ah/missao-rio/make-batismos/

  - name: Edit Pages
    url: /_ah/missao-rio/edit-pages/
