// Code generated by "stringer -type Typ"; DO NOT EDIT.

package main

import "strconv"

const _Typ_name = "PlaceholderIdentSemicolonFconstIconstSconstBconst"

var _Typ_index = [...]uint8{0, 11, 16, 25, 31, 37, 43, 49}

func (i Typ) String() string {
	i -= 1
	if i < 0 || i >= Typ(len(_Typ_index)-1) {
		return "Typ(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Typ_name[_Typ_index[i]:_Typ_index[i+1]]
}
