from django.conf.urls.defaults import *

urlpatterns = patterns('',
	(r'^list/(?P<loc_id>\d*)/?$', 'darc.ads.views.list'),
	(r'^info/(?P<loc_id>\d*)/?$', 'darc.ads.views.info'),
	(r'^blog/', include('darc.blog.urls')),
	(r'^login/', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}),
	(r'^logout/', 'django.contrib.auth.views.logout', {'template_name': 'main/logout-success.html'}),
	(r'^register/', 'darc.main.views.register'),
	(r'^account/$', 'darc.main.views.account'),
	(r'^account/change/$', 'darc.main.views.password_change'),
	(r'^account/pay/$', 'darc.main.views.pay'),
	(r'^ads/$', 'darc.ads.views.index'),
	(r'^ads/upload/$', 'darc.ads.views.upload'),
	(r'^ads/checkoutdata/$', 'darc.ads.views.checkoutdata'),
	(r'^ads/checkout/$', 'darc.ads.views.checkout'),
	(r'^mod/$', 'darc.mod.views.index'),
	(r'^mod/categories/$', 'darc.mod.views.categories'),
	(r'^mod/checkads/$', 'darc.mod.views.checkads'),
	(r'^mod/s3/$', 'darc.mod.views.s3'),
	(r'^mod/users/$', 'darc.mod.views.users'),
	(r'^mod/users/(?P<user_id>\d+)/$', 'darc.mod.views.user_detail'),
	(r'^mod/reservations/$', 'darc.mod.views.reservations'),

	(r'^templates/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'templates'}),
	(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'uploads'}),
	(r'^admin/', include('django.contrib.admin.urls')),
	(r'^$', 'darc.main.views.index'),
)
