<?php
//1 ... Repeat this code block for all 13 possible cart combos (13 combos is what the cart can support visually)
$totalCost1 = $_POST['totalCost1'];
$comboName1 = $_POST['comboName1'];
$adName1 = $_POST['adName1'];
$locationName1 = $_POST['locationName1'];
$startDate1 = $_POST['startDate1'];
$endDate1 = $_POST['endDate1'];

//2 ...
//3 ...
//4 ...
//5 ...
//6 ...
//7 ...
//8 ...
//9 ...
//10 ...
//11 ...
//12 ...
//13 ...

//Do your thing with all the data (maybe put it in a database so you can pass it over to the checkoutpage.php)

?>
